import { defineConfig } from "tsup";

export default defineConfig({
	entry: [
		"src/index.ts",
		"src/extra/index.ts",
		"src/extra/interval.ts",
		"src/extra/fromIter.ts",
		"src/extra/fromEvent.ts",
		"src/extra/fromPromise.ts",
		"src/extra/fromObs.ts",
		"src/extra/take.ts",
		"src/extra/skip.ts",
		"src/extra/merge.ts",
		"src/extra/combine.ts",
		"src/extra/concat.ts",
		"src/extra/flat.ts",
		"src/extra/forEach.ts",
		"src/extra/share.ts",
		"src/extra/map.ts",
		"src/extra/filter.ts",
		"src/extra/scan.ts",
		"src/extra/takeUntil.ts",
		"src/extra/takeWhile.ts",
		"src/extra/switchMap.ts",
		"src/extra/concatMap.ts",
		"src/extra/exhaustMap.ts",
		"src/extra/debounce.ts",
		"src/extra/throttle.ts",
		"src/extra/distinctUntilChanged.ts",
		"src/extra/startWith.ts",
		"src/extra/pairwise.ts",
		"src/extra/delay.ts",
		"src/extra/buffer.ts",
		"src/extra/bufferTime.ts",
		"src/extra/rescue.ts",
		"src/extra/sample.ts",
		"src/extra/timeout.ts",
		"src/extra/subject.ts",
		"src/extra/remember.ts",
		"src/extra/tap.ts",
		"src/extra/subscribe.ts",
		"src/extra/pipeRaw.ts",
		"src/extra/of.ts",
		"src/extra/empty.ts",
		"src/extra/throwError.ts",
		"src/extra/never.ts",
		"src/extra/first.ts",
		"src/extra/last.ts",
		"src/extra/find.ts",
		"src/extra/elementAt.ts",
		"src/extra/partition.ts",
		"src/extra/repeat.ts",
		"src/patterns/createStore/index.ts",
		"src/patterns/chatStream/index.ts",
		"src/patterns/memoryStore/index.ts",
		"src/patterns/rateLimiter/index.ts",
		"src/patterns/undoRedo/index.ts",
		"src/patterns/pagination/index.ts",
		"src/patterns/formField/index.ts",
		"src/patterns/textBuffer/index.ts",
		"src/patterns/textEditor/index.ts",
		"src/compat/nanostores/index.ts",
		"src/compat/signals/index.ts",
		"src/compat/jotai/index.ts",
		"src/compat/zustand/index.ts",
		"src/utils/index.ts",
		"src/data/index.ts",
		"src/memory/index.ts",
		"src/orchestrate/index.ts",
		"src/patterns/toolCallState/index.ts",
		"src/patterns/hybridRoute/index.ts",
		"src/patterns/agentLoop/index.ts",
		"src/adapters/index.ts",
		"src/adapters/webhook.ts",
		"src/adapters/websocket.ts",
		"src/adapters/sse.ts",
		"src/adapters/http.ts",
		"src/adapters/llm.ts",
		"src/adapters/mcp.ts",
		"src/extra/streamParse.ts",
	],
	format: ["esm", "cjs"],
	dts: true,
	clean: true,
	minify: true,
	sourcemap: false,
});
